# Generated by Django 6.0.5 on 2026-06-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participant",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="participant",
            name="glucose",
        ),
        migrations.AddField(
            model_name="participant",
            name="CholCheck",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="participant",
            name="Diffwalk",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="participant",
            name="Education",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="participant",
            name="Fruits",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="participant",
            name="HeartDiseaseorAttack",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="participant",
            name="HighChol",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="participant",
            name="Hvyalcohol",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="participant",
            name="MentHlth",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="participant",
            name="Nodocbccost",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="participant",
            name="PhysHlth",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="participant",
            name="Veggies",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="participant",
            name="any_hlthcare",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="participant",
            name="blood_pressure",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="participant",
            name="gen_hlth",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="participant",
            name="income",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="participant",
            name="physical_activity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="participant",
            name="sex",
            field=models.CharField(default="Male", max_length=6),
        ),
        migrations.AddField(
            model_name="participant",
            name="smoker",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="participant",
            name="stroke",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="participant",
            name="age",
            field=models.IntegerField(default=0),
        ),
    ]
