# Generated by Django 6.0.5 on 2026-06-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "healthapp",
            "0002_remove_participant_gender_remove_participant_glucose_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="participant",
            old_name="age",
            new_name="Age",
        ),
        migrations.RenameField(
            model_name="participant",
            old_name="any_hlthcare",
            new_name="AnyHealthcare",
        ),
        migrations.RenameField(
            model_name="participant",
            old_name="Diffwalk",
            new_name="DiffWalk",
        ),
        migrations.RenameField(
            model_name="participant",
            old_name="gen_hlth",
            new_name="GenHlth",
        ),
        migrations.RenameField(
            model_name="participant",
            old_name="blood_pressure",
            new_name="HighBP",
        ),
        migrations.RenameField(
            model_name="participant",
            old_name="Hvyalcohol",
            new_name="HvyAlcoholConsump",
        ),
        migrations.RenameField(
            model_name="participant",
            old_name="income",
            new_name="Income",
        ),
        migrations.RenameField(
            model_name="participant",
            old_name="physical_activity",
            new_name="PhysActivity",
        ),
        migrations.RenameField(
            model_name="participant",
            old_name="sex",
            new_name="Sex",
        ),
        migrations.RenameField(
            model_name="participant",
            old_name="smoker",
            new_name="Smoker",
        ),
        migrations.RenameField(
            model_name="participant",
            old_name="stroke",
            new_name="Stroke",
        ),
        migrations.RemoveField(
            model_name="participant",
            name="bmi",
        ),
        migrations.AddField(
            model_name="participant",
            name="BMI",
            field=models.FloatField(default=0.0),
        ),
    ]
