# Generated by Django 6.0.5 on 2026-06-21 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthapp", "0003_rename_age_participant_age_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="Sex",
            field=models.IntegerField(default=0),
        ),
    ]
