# Generated by Django 6.0.5 on 2026-06-21 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthapp", "0004_alter_participant_sex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="BMI",
            field=models.IntegerField(default=0),
        ),
    ]
