# Generated by Django 6.0.5 on 2026-06-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthapp", "0005_alter_participant_bmi"),
    ]

    operations = [
        migrations.CreateModel(
            name="Participant2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Pregnancies", models.IntegerField(default=0)),
                ("Glucose", models.FloatField(default=0)),
                ("BloodPressure", models.FloatField(default=0)),
                ("SkinThickness", models.FloatField(default=0)),
                ("Insulin", models.FloatField(default=0)),
                ("BMI", models.FloatField(default=0.0)),
                ("DiabetesPedigreeFunction", models.FloatField(default=0.0)),
                ("Age", models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name="participant",
            old_name="Nodocbccost",
            new_name="NoDocbcCost",
        ),
    ]
