# Generated by Django 6.0.5 on 2026-06-23 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthapp", "0006_participant2_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Participant3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Sex", models.IntegerField(default=0)),
                ("Age", models.IntegerField(default=0)),
                ("Height", models.FloatField(default=0)),
                ("Weight", models.FloatField(default=0)),
                ("BMI", models.FloatField(default=0.0)),
                ("Smoking", models.FloatField(default=0.0)),
                ("Alcohol", models.IntegerField(default=0)),
                ("Duration", models.FloatField(default=0.0)),
                ("DMac", models.IntegerField(default=0)),
                ("DMic", models.IntegerField(default=0)),
                ("Comorbidities", models.IntegerField(default=0)),
                ("HypoglycemicAgent", models.IntegerField(default=0)),
                ("FPGlucose", models.FloatField(default=0.0)),
                ("PPGlucose", models.FloatField(default=0.0)),
                ("FCpeptide", models.FloatField(default=0.0)),
                ("Ppeptide", models.FloatField(default=0.0)),
                ("Fastinsulin", models.FloatField(default=0.0)),
                ("Postinsulin", models.FloatField(default=0.0)),
                ("HbA1c", models.IntegerField(default=0)),
                ("GAlbumin", models.FloatField(default=0.0)),
                ("TCholesterol", models.FloatField(default=0.0)),
                ("Triglyceride", models.FloatField(default=0.0)),
                ("HDLC", models.FloatField(default=0.0)),
                ("LDLC", models.FloatField(default=0.0)),
                ("Creatinine", models.FloatField(default=0.0)),
                ("EGFR", models.IntegerField(default=0.0)),
                ("UAcid", models.FloatField(default=0.0)),
                ("BUN", models.FloatField(default=0.0)),
                ("Hypoglycemia", models.IntegerField(default=0.0)),
            ],
        ),
        migrations.RenameModel(
            old_name="Person",
            new_name="User",
        ),
    ]
