# Generated by Django 6.0.5 on 2026-06-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthapp", "0007_participant3_rename_person_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="BMIcal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Height", models.FloatField(default=0.0)),
                ("Weight", models.FloatField(default=0.0)),
            ],
        ),
    ]
